== callable vs runnable vs future
Функциональные интерфейсы Callable и Runnable используются для выполнения кода в отдельном потоке, но есть различия в том, как они предоставляют результат выполнения и обрабатывают исключения.

=== Runnable
- Возвращаемое значение: нет
- Исключения: не может выбрасывать проверяемые исключения (за исключением тех, которые являются подклассами RuntimeException)
- Метод run()

=== Callable
- Возвращаемое значение: может возвращать результат выполнения задачи
- Исключения: может выбрасывать проверяемые исключения
- Метод call()

=== Future
Благодаря этому интерфейсу можно взаимодействовать с результатами асинхронных вычислений. Future показывает результат выполнения асинхронной операции и предоставляет методы для проверки завершения операции, ожидания её завершения и извлечения результата.
[source,java]
----
Callable<Integer> callableTask = () -> {
System.out.println("Выполняется в отдельном потоке");
// Какая-то вычислительная работа
return 42;
};
// Определяем пул из трех потоков
ExecutorService executor = Executors.newFixedThreadPool(3);
// Передаем Callable задачу в ExecutorService
Future<Integer> future = executor.submit(callableTask);
// Ждем завершения выполнения и получаем результат
Integer result = future.get();
----
=== CompletableFuture
CompletableFuture - расширение интерфейса Future, введенное в Java 8, предоставляет широкий набор методов для выполнения различных операций над результатами асинхронных задач (пост-обработка результата, комбинация результатов, обработка исключений).
