Maven - это инструмент для сборки Java проекта: скачивание дополнительных библиотек, компиляции,
создания jar, генерации документации.

== 3 жизненных цикла сборки Maven:
clean (очистки проекта, удаление файлов, оставшихся от предыдущей сборки),
default (основной),
site (генерации проектной документации)

Каждый цикл содержит фазы (как обед из нескольких блюд: первое, второе, десерт и т.д):

для default-цикла

. validate
. compile
. test
. package
. verify
. install
. deploy

Плагины привязаны к фазе и выполняют на ней свои цели.
Цель - это действие, которое плагин может выполнить. Целей может быть несколько.

== Некоторые плагины:
. maven-archetype-plugin - по существующему шаблону создавать новые проекты
. maven-compiler-plugin - компиляция проекта
. maven-resources-plugin - плагин копирования ресурсов (перед сборкой все ресурсы - файлы изображений,
.properties - скопировать в директорию target)
. maven-surefire-plugin - для запуска тестов и генерации отчетов по результатам их выполнения
. spring-boot-maven-plugin - упаковка в исполняемый jar/war (repackage-цель), запуск spring-boot приложения и др.
. asciidoctor-maven-plugin - плагин конвертации ascii-документации в html/pdf и пр.
. swagger-maven-plugin - для генерации json-спецификации проекта
. springdoc-openapi-maven-plugin - для генерации YAML-спецификации при сборке проекта
. maven-dependency-plugin - поиск дублирующихся зависимостей (tree/analyze-duplicate)
. maven-enforcer-plugin - запрет сборки при дублировании зависимостей

== maven java api
MOJO API (именование по аналогии с POJO "plain old java object")
MOJO API позволяет создавать кастомные maven-плагины, где mojo - определенным образом
аннотированный java-класс (@Mojo), реализующий интерфейс AbstractMojo (метод execute())
и тем самым представляющий в итоге цель плагина.
