= Паттерны микросервисной архитектуры

* Паттерны декомпозиции на микросервисы

. Шаблон «Разбиение по бизнес-возможностям» (Decompose By Business Capability):
это определение бизнес-возможностей приложения и создание по одному микросервису на каждую из них.
Бизнес-возможности представляют собой функции, которые будут доступны пользователям при работе с приложением

. Шаблон «Разбиение по поддоменам» (Decompose By Subdomain):
основан на концепциях предметно-ориентированного проектирования (Domain-Driven Design, DDD).
Каждый микросервис будет разрабатываться внутри ограниченного контекста (Bounded Context).
Основная задача при использовании DDD-подхода — подобрать поддомены и границы между ними так,
чтобы они были максимально независимы друг от друга.

* Паттерны рефакторинга для перехода на микросервисы

. "Душитель" (Strangler)
Этот шаблон означает миграцию монолитного приложения на микросервисную архитектуру путем
постепенного переноса существующих функций в микросервисы.
После переноса всех функций монолитное приложение полностью выводится из эксплуатации.

* Паттерны управления данными в микросервисной архитектуре

. Шаблон «База данных на сервис» (Database Per Service)
. Shared Database («Разделяемая база данных»)
. Шаблон «API-композиция» (API Composition)
вариант получения данных из нескольких сервисов после применения к ним паттерна Database Per Service.
Он предлагает создать отдельное API, которое будет вызывать необходимые сервисы, владеющие данными,
и выполнять соединение полученных от них результатов в памяти
. CQRS (Command Query Responsibility Segregation)
паттерн предлагает отделить изменение данных (Command) от чтения данных (Query)
. Saga
управление распределенными транзакциями в микросервисной архитектуре

* Паттерны коммуникации микросервисов

. Шаблон «API-шлюз» (API Gateway)
применение шлюза, который находится между клиентским приложением и микросервисами, обеспечивая единую точку входа для клиента

. Idempotent consumer: потребитель должен быть идемпотентным,
т.е результат многократной обработки одного и того же сообщения должен быть таким же,
как и при однократной обработке сообщения.
Если потребитель не является идемпотентным, множественные вызовы могут вызвать ошибки.

* Сквозная функциональность (cross-cutting concern)
. Шаблон: Microservice Chassis - микросервисное шасси:
выделение общеиспользуемой функциональности/инфраструктуры для наиболее удобного переиспользования
при создании многочисленных микросервисов (пример - шаблон модуля):
безопасность, распределенная трассировка, логи, асинхронное взаимодействие и т.д

. Внешняя конфигурация (не хранить конфиги в кодовой базе)

. Распределенная трассировка