= RED и USE — методики мониторинга системы

== USE
USE - фокусируется на ресурсах инфраструктуры, метод для анализа низкоуровневых метрик.
Он измеряет, насколько загружены физические ресурсы, перегружены ли они и возникают ли сбои.
Акроним USE: Utilization, Saturation, Errors.
Пример: утилизация процессора, количество свободного места, памяти, превышение допустимой температуры оборудования.

. Utilization - утилизация/использование/загрузка - доля используемого ресурса за определенное время (в процентах). +
Показывает насколько эффективно используется ресурс. Если утилизация близка к 100%, это может указывать на необходимость оптимизации или увеличения ресурсов. +
Пример: использование CPU (LA), утилизация оперативной памяти RAM, пул соединений с БД
. Saturation - насыщение - объём работы, который ресурс не может обслужить. +
Обычно представляют эту метрику как длину очереди. +
Пример: размер очереди RabbitMQ, количество запросов к БД, которые ожидают выполнения, потому что пул исчерпан.
. Errors - ошибки, которые произошли во время использования ресурса. +
Пример: OutOfMemoryError для RAM, ошибки при попытке получить соединение с БД - исключение SQLTransientConnectionException, если пул соединений исчерпан.

== RED
RED - метод представляет то, как наш сервис обрабатывает внешние запросы.
Акроним RED: Rate, Errors, Duration.

. Rate - количество запросов в секунду, которые наш сервис обрабатывает
. Errors - количество неудачных запросов в секунду
. Duration - распределение количества времени, которое занимает каждый запрос

== The Four Golden Signals
Подход к мониторингу из Service (Site) Reliability Engineering - проектирования надежности сервиса (от Google), выделяющий 4 ключевых аспекта работы системы:

.Latency (Задержка)
Время, которое требуется для обработки запроса.
Включает как успешные запросы, так и запросы с ошибками.
Пример: среднее время ответа API.

.Traffic (Трафик)
Объем нагрузки на систему.
Измеряется в запросах в секунду, количестве пользователей или объеме данных.
Пример: количество HTTP-запросов в секунду.

.Errors (Ошибки)
Доля запросов, которые завершились с ошибкой.
Пример: процент HTTP 5xx ошибок или таймаутов.

.Saturation (Насыщение)
Насколько система близка к своим пределам.
Пример: использование CPU, памяти, заполненность пула соединений.
