= Spring Boot

== Разработка автоконфигураций
Стартеры Spring Boot — это, предварительно упакованные наборы зависимостей и сконфигурированных бинов для обеспечения определённой функциональности. Например, доступа к базе данных или безопасности.

. Схема именования официальных стартеров spring-boot-starter-*, где * это конкретный тип приложения.
Сторонний стартер обычно начинается с названия проекта. Например, my-demo-spring-boot-starter.
. В pom-файл добавляются зависимости spring-boot-starter и spring-boot-configuration-processor (для подсказок описания свойств application.properties этот процессор аннотаций создаст файл META-INF/spring-configuration-metadata.json, который содержит метаданные о параметрах конфигурации в классах с properties - @ConfigurationProperties).
. Добавляются зависимости вашей библиотеки.
. Создается обычный класс конфигурации Spring с нужными бинами.
. Самое важное: в папке resources создаём папку META-INF, в ней папку spring, и в ней файл org.springframework.boot.autoconfigure.AutoConfiguration.imports (ранее, до Spring Boot 2.7 был нужен spring.factories и в нем поле org.springframework.boot.autoconfigure.EnableAutoConfiguration=...).
Этот файл должен содержать перечисление конфигураций.
SpringBoot автоматически найдёт этот файл, возьмёт перечисленные конфигурации и создаст указанные в них бины, добавив их в контекст. Так класс конфигурации превращается в класс автоконфигурации.
