== Установка флага прерывания
В этом случае, когда происходит InterruptedException, устанавливается флаг прерывания текущего потока. Этот подход позволяет передать информацию о прерывании выше по стеку вызовов, что полезно, если текущий метод не знает, как правильно обработать прерывание.
[source,java]
----
try {
   // Код, который может вызвать InterruptedException
} catch (InterruptedException e) {
   // Установка флага прерывания (true), потому что после catch он сбросился в false
   Thread.currentThread().interrupt();
----
== Проброс RuntimeException
В этом случае при возникновении InterruptedException выбрасывается непроверяемое исключение RuntimeException. Этот подход применяется, когда обработка InterruptedException в текущем контексте невозможна или нежелательна, и требуется прервать выполнение текущего блока кода.
[source,java]
----
try {
   // Код, который может вызвать InterruptedException
} catch (InterruptedException e) {
   throw new RuntimeException(e);
}
----
Выбор между этими двумя способами зависит от конкретной задачи. Первый подход обычно используется, когда есть вероятность, что прерывание потока будет корректно обработано на более высоком уровне. Второй подход применяется, когда нет уверенности, что прерывание будет корректно обработано, и лучше прервать выполнение кода, выбросив исключение.

link:../src/main/java/ru/venediktov/javacore/threads/InterruptThread.java[InterruptThread demo]
