== Состояние гонки
race condition — это ситуация в многопоточной среде (ошибка), когда два или более потока пытаются изменить общее состояние приложения (переменную) одновременно и порядок выполнения операций в критической секции не определён, это приводит к некорректным результатам

== 2 типа условий состояния гонки

=== Read-modify-write
Состояние гонки типа Read-Modify-Write в Java возникает, когда несколько потоков одновременно читают значение переменной (из памяти в регистры CPU), модифицируют его и записывают обратно (в память). Это может привести к некорректным результатам, так как операции чтения и записи не атомарны.
[source,java]
----
private int counter = 0;

public void increment() {
    int temp = counter; // Read
    temp = temp + 1;    // Modify
    counter = temp;     // Write
}
----
=== Check-then-act
Состояние гонки типа Check-then-Act в Java возникает, когда несколько потоков проверяют условие и затем действуют на основе этой проверки. Если между проверкой условия и действием происходит изменение состояния другим потоком, это может привести к некорректным результатам.
[source,java]
----
private boolean flag = false;

public void checkThenAct() {
    if (!flag) { // Check
    // Действие, зависящее от флага
    flag = true; // Act
    }
}
----
